import { Countries } from './country.model';

export var countries: Countries[] = [
  { code: "AF", code3: "AFG", name: "Afghanistan", dialCode: "+93", flag: "https://flagcdn.com/w40/af.png" },
  { code: "AL", code3: "ALB", name: "Albania", dialCode: "+355", flag: "https://flagcdn.com/w40/al.png" },
  { code: "DZ", code3: "DZA", name: "Algeria", dialCode: "+213", flag: "https://flagcdn.com/w40/dz.png" },
  { code: "AS", code3: "ASM", name: "American Samoa", dialCode: "+1-684", flag: "https://flagcdn.com/w40/as.png" },
  { code: "AD", code3: "AND", name: "Andorra", dialCode: "+376", flag: "https://flagcdn.com/w40/ad.png" },
  { code: "AO", code3: "AGO", name: "Angola", dialCode: "+244", flag: "https://flagcdn.com/w40/ao.png" },
  { code: "AI", code3: "AIA", name: "Anguilla", dialCode: "+1-264", flag: "https://flagcdn.com/w40/ai.png" },
  { code: "AQ", code3: "ATA", name: "Antarctica", dialCode: "+672", flag: "https://flagcdn.com/w40/aq.png" },
  { code: "AG", code3: "ATG", name: "Antigua and Barbuda", dialCode: "+1-268", flag: "https://flagcdn.com/w40/ag.png" },
  { code: "AR", code3: "ARG", name: "Argentina", dialCode: "+54", flag: "https://flagcdn.com/w40/ar.png" },
  { code: "AM", code3: "ARM", name: "Armenia", dialCode: "+374", flag: "https://flagcdn.com/w40/am.png" },
  { code: "AW", code3: "ABW", name: "Aruba", dialCode: "+297", flag: "https://flagcdn.com/w40/aw.png" },
  { code: "AU", code3: "AUS", name: "Australia", dialCode: "+61", flag: "https://flagcdn.com/w40/au.png" },
  { code: "AT", code3: "AUT", name: "Austria", dialCode: "+43", flag: "https://flagcdn.com/w40/at.png" },
  { code: "AZ", code3: "AZE", name: "Azerbaijan", dialCode: "+994", flag: "https://flagcdn.com/w40/az.png" },
  { code: "BS", code3: "BHS", name: "Bahamas (the)", dialCode: "+1-242", flag: "https://flagcdn.com/w40/bs.png" },
  { code: "BH", code3: "BHR", name: "Bahrain", dialCode: "+973", flag: "https://flagcdn.com/w40/bh.png" },
  { code: "BD", code3: "BGD", name: "Bangladesh", dialCode: "+880", flag: "https://flagcdn.com/w40/bd.png" },
  { code: "BB", code3: "BRB", name: "Barbados", dialCode: "+1-246", flag: "https://flagcdn.com/w40/bb.png" },
  { code: "BY", code3: "BLR", name: "Belarus", dialCode: "+375", flag: "https://flagcdn.com/w40/by.png" },
  { code: "BE", code3: "BEL", name: "Belgium", dialCode: "+32", flag: "https://flagcdn.com/w40/be.png" },
  { code: "BZ", code3: "BLZ", name: "Belize", dialCode: "+501", flag: "https://flagcdn.com/w40/bz.png" },
  { code: "BJ", code3: "BEN", name: "Benin", dialCode: "+229", flag: "https://flagcdn.com/w40/bj.png" },
  { code: "BM", code3: "BMU", name: "Bermuda", dialCode: "+1-441", flag: "https://flagcdn.com/w40/bm.png" },
  { code: "BT", code3: "BTN", name: "Bhutan", dialCode: "+975", flag: "https://flagcdn.com/w40/bt.png" },
  { code: "BO", code3: "BOL", name: "Bolivia (Plurinational State of)", dialCode: "+591", flag: "https://flagcdn.com/w40/bo.png" },
  { code: "BQ", code3: "BES", name: "Bonaire, Sint Eustatius and Saba", dialCode: "+599", flag: "https://flagcdn.com/w40/bq.png" },
  { code: "BA", code3: "BIH", name: "Bosnia and Herzegovina", dialCode: "+387", flag: "https://flagcdn.com/w40/ba.png" },
  { code: "BW", code3: "BWA", name: "Botswana", dialCode: "+267", flag: "https://flagcdn.com/w40/bw.png" },
  { code: "BV", code3: "BVT", name: "Bouvet Island", dialCode: "+47", flag: "https://flagcdn.com/w40/bv.png" },
  { code: "BR", code3: "BRA", name: "Brazil", dialCode: "+55", flag: "https://flagcdn.com/w40/br.png" },
  { code: "IO", code3: "IOT", name: "British Indian Ocean Territory (the)", dialCode: "+246", flag: "https://flagcdn.com/w40/io.png" },
  { code: "BN", code3: "BRN", name: "Brunei Darussalam", dialCode: "+673", flag: "https://flagcdn.com/w40/bn.png" },
  { code: "BG", code3: "BGR", name: "Bulgaria", dialCode: "+359", flag: "https://flagcdn.com/w40/bg.png" },
  { code: "BF", code3: "BFA", name: "Burkina Faso", dialCode: "+226", flag: "https://flagcdn.com/w40/bf.png" },
  { code: "BI", code3: "BDI", name: "Burundi", dialCode: "+257", flag: "https://flagcdn.com/w40/bi.png" },
  { code: "CV", code3: "CPV", name: "Cabo Verde", dialCode: "+238", flag: "https://flagcdn.com/w40/cv.png" },
  { code: "KH", code3: "KHM", name: "Cambodia", dialCode: "+855", flag: "https://flagcdn.com/w40/kh.png" },
  { code: "CM", code3: "CMR", name: "Cameroon", dialCode: "+237", flag: "https://flagcdn.com/w40/cm.png" },
  { code: "CA", code3: "CAN", name: "Canada", dialCode: "+1", flag: "https://flagcdn.com/w40/ca.png" },
  { code: "KY", code3: "CYM", name: "Cayman Islands (the)", dialCode: "+1-345", flag: "https://flagcdn.com/w40/ky.png" },
  { code: "CF", code3: "CAF", name: "Central African Republic (the)", dialCode: "+236", flag: "https://flagcdn.com/w40/cf.png" },
  { code: "TD", code3: "TCD", name: "Chad", dialCode: "+235", flag: "https://flagcdn.com/w40/td.png" },
  { code: "CL", code3: "CHL", name: "Chile", dialCode: "+56", flag: "https://flagcdn.com/w40/cl.png" },
  { code: "CN", code3: "CHN", name: "China", dialCode: "+86", flag: "https://flagcdn.com/w40/cn.png" },
  { code: "CX", code3: "CXR", name: "Christmas Island", dialCode: "+61", flag: "https://flagcdn.com/w40/cx.png" },
  { code: "CC", code3: "CCK", name: "Cocos (Keeling) Islands (the)", dialCode: "+61", flag: "https://flagcdn.com/w40/cc.png" },
  { code: "CO", code3: "COL", name: "Colombia", dialCode: "+57", flag: "https://flagcdn.com/w40/co.png" },
  { code: "KM", code3: "COM", name: "Comoros (the)", dialCode: "+269", flag: "https://flagcdn.com/w40/km.png" },
  { code: "CD", code3: "COD", name: "Congo (the Democratic Republic of the)", dialCode: "+243", flag: "https://flagcdn.com/w40/cd.png" },
  { code: "CG", code3: "COG", name: "Congo (the)", dialCode: "+242", flag: "https://flagcdn.com/w40/cg.png" },
  { code: "CK", code3: "COK", name: "Cook Islands (the)", dialCode: "+682", flag: "https://flagcdn.com/w40/ck.png" },
  { code: "CR", code3: "CRI", name: "Costa Rica", dialCode: "+506", flag: "https://flagcdn.com/w40/cr.png" },
  { code: "HR", code3: "HRV", name: "Croatia", dialCode: "+385", flag: "https://flagcdn.com/w40/hr.png" },
  { code: "CU", code3: "CUB", name: "Cuba", dialCode: "+53", flag: "https://flagcdn.com/w40/cu.png" },
  { code: "CW", code3: "CUW", name: "Curaçao", dialCode: "+599", flag: "https://flagcdn.com/w40/cw.png" },
  { code: "CY", code3: "CYP", name: "Cyprus", dialCode: "+357", flag: "https://flagcdn.com/w40/cy.png" },
  { code: "CZ", code3: "CZE", name: "Czechia", dialCode: "+420", flag: "https://flagcdn.com/w40/cz.png" },
  { code: "CI", code3: "CIV", name: "Côte d'Ivoire", dialCode: "+225", flag: "https://flagcdn.com/w40/ci.png" },
  { code: "DK", code3: "DNK", name: "Denmark", dialCode: "+45", flag: "https://flagcdn.com/w40/dk.png" },
  { code: "DJ", code3: "DJI", name: "Djibouti", dialCode: "+253", flag: "https://flagcdn.com/w40/dj.png" },
  { code: "DM", code3: "DMA", name: "Dominica", dialCode: "+1-767", flag: "https://flagcdn.com/w40/dm.png" },
  { code: "DO", code3: "DOM", name: "Dominican Republic (the)", dialCode: "+1-809, +1-829, +1-849", flag: "https://flagcdn.com/w40/do.png" },
  { code: "EC", code3: "ECU", name: "Ecuador", dialCode: "+593", flag: "https://flagcdn.com/w40/ec.png" },
  { code: "EG", code3: "EGY", name: "Egypt", dialCode: "+20", flag: "https://flagcdn.com/w40/eg.png" },
  { code: "SV", code3: "SLV", name: "El Salvador", dialCode: "+503", flag: "https://flagcdn.com/w40/sv.png" },
  { code: "GQ", code3: "GNQ", name: "Equatorial Guinea", dialCode: "+240", flag: "https://flagcdn.com/w40/gq.png" },
  { code: "ER", code3: "ERI", name: "Eritrea", dialCode: "+291", flag: "https://flagcdn.com/w40/er.png" },
  { code: "EE", code3: "EST", name: "Estonia", dialCode: "+372", flag: "https://flagcdn.com/w40/ee.png" },
  { code: "SZ", code3: "SWZ", name: "Eswatini", dialCode: "+268", flag: "https://flagcdn.com/w40/sz.png" },
  { code: "ET", code3: "ETH", name: "Ethiopia", dialCode: "+251", flag: "https://flagcdn.com/w40/et.png" },
  { code: "FK", code3: "FLK", name: "Falkland Islands (the) [Malvinas]", dialCode: "+500", flag: "https://flagcdn.com/w40/fk.png" },
  { code: "FO", code3: "FRO", name: "Faroe Islands (the)", dialCode: "+298", flag: "https://flagcdn.com/w40/fo.png" },
  { code: "FJ", code3: "FJI", name: "Fiji", dialCode: "+679", flag: "https://flagcdn.com/w40/fj.png" },
  { code: "FI", code3: "FIN", name: "Finland", dialCode: "+358", flag: "https://flagcdn.com/w40/fi.png" },
  { code: "FR", code3: "FRA", name: "France", dialCode: "+33", flag: "https://flagcdn.com/w40/fr.png" },
  { code: "GF", code3: "GUF", name: "French Guiana", dialCode: "+594", flag: "https://flagcdn.com/w40/gf.png" },
  { code: "PF", code3: "PYF", name: "French Polynesia", dialCode: "+689", flag: "https://flagcdn.com/w40/pf.png" },
  { code: "TF", code3: "ATF", name: "French Southern Territories (the)", dialCode: "+262", flag: "https://flagcdn.com/w40/tf.png" },
  { code: "GA", code3: "GAB", name: "Gabon", dialCode: "+241", flag: "https://flagcdn.com/w40/ga.png" },
  { code: "GM", code3: "GMB", name: "Gambia (the)", dialCode: "+220", flag: "https://flagcdn.com/w40/gm.png" },
  { code: "GE", code3: "GEO", name: "Georgia", dialCode: "+995", flag: "https://flagcdn.com/w40/ge.png" },
  { code: "DE", code3: "DEU", name: "Germany", dialCode: "+49", flag: "https://flagcdn.com/w40/de.png" },
  { code: "GH", code3: "GHA", name: "Ghana", dialCode: "+233", flag: "https://flagcdn.com/w40/gh.png" },
  { code: "GI", code3: "GIB", name: "Gibraltar", dialCode: "+350", flag: "https://flagcdn.com/w40/gi.png" },
  { code: "GR", code3: "GRC", name: "Greece", dialCode: "+30", flag: "https://flagcdn.com/w40/gr.png" },
  { code: "GL", code3: "GRL", name: "Greenland", dialCode: "+299", flag: "https://flagcdn.com/w40/gl.png" },
  { code: "GD", code3: "GRD", name: "Grenada", dialCode: "+1-473", flag: "https://flagcdn.com/w40/gd.png" },
  { code: "GP", code3: "GLP", name: "Guadeloupe", dialCode: "+590", flag: "https://flagcdn.com/w40/gp.png" },
  { code: "GU", code3: "GUM", name: "Guam", dialCode: "+1-671", flag: "https://flagcdn.com/w40/gu.png" },
  { code: "GT", code3: "GTM", name: "Guatemala", dialCode: "+502", flag: "https://flagcdn.com/w40/gt.png" },
  { code: "GG", code3: "GGY", name: "Guernsey", dialCode: "+44-1481", flag: "https://flagcdn.com/w40/gg.png" },
  { code: "GN", code3: "GIN", name: "Guinea", dialCode: "+224", flag: "https://flagcdn.com/w40/gn.png" },
  { code: "GW", code3: "GNB", name: "Guinea-Bissau", dialCode: "+245", flag: "https://flagcdn.com/w40/gw.png" },
  { code: "GY", code3: "GUY", name: "Guyana", dialCode: "+592", flag: "https://flagcdn.com/w40/gy.png" },
  { code: "HT", code3: "HTI", name: "Haiti", dialCode: "+509", flag: "https://flagcdn.com/w40/ht.png" },
  { code: "HM", code3: "HMD", name: "Heard Island and McDonald Islands", dialCode: "+672", flag: "https://flagcdn.com/w40/hm.png" },
  { code: "VA", code3: "VAT", name: "Holy See (the)", dialCode: "+379", flag: "https://flagcdn.com/w40/va.png" },
  { code: "HN", code3: "HND", name: "Honduras", dialCode: "+504", flag: "https://flagcdn.com/w40/hn.png" },
  { code: "HK", code3: "HKG", name: "Hong Kong", dialCode: "+852", flag: "https://flagcdn.com/w40/hk.png" },
  { code: "HU", code3: "HUN", name: "Hungary", dialCode: "+36", flag: "https://flagcdn.com/w40/hu.png" },
  { code: "IS", code3: "ISL", name: "Iceland", dialCode: "+354", flag: "https://flagcdn.com/w40/is.png" },
  { code: "IN", code3: "IND", name: "India", dialCode: "+91", flag: "https://flagcdn.com/w40/in.png" },
  { code: "ID", code3: "IDN", name: "Indonesia", dialCode: "+62", flag: "https://flagcdn.com/w40/id.png" },
  { code: "IR", code3: "IRN", name: "Iran (Islamic Republic of)", dialCode: "+98", flag: "https://flagcdn.com/w40/ir.png" },
  { code: "IQ", code3: "IRQ", name: "Iraq", dialCode: "+964", flag: "https://flagcdn.com/w40/iq.png" },
  { code: "IE", code3: "IRL", name: "Ireland", dialCode: "+353", flag: "https://flagcdn.com/w40/ie.png" },
  { code: "IM", code3: "IMN", name: "Isle of Man", dialCode: "+44-1624", flag: "https://flagcdn.com/w40/im.png" },
  { code: "IL", code3: "ISR", name: "Israel", dialCode: "+972", flag: "https://flagcdn.com/w40/il.png" },
  { code: "IT", code3: "ITA", name: "Italy", dialCode: "+39", flag: "https://flagcdn.com/w40/it.png" },
  { code: "JM", code3: "JAM", name: "Jamaica", dialCode: "+1-876", flag: "https://flagcdn.com/w40/jm.png" },
  { code: "JP", code3: "JPN", name: "Japan", dialCode: "+81", flag: "https://flagcdn.com/w40/jp.png" },
  { code: "JE", code3: "JEY", name: "Jersey", dialCode: "+44-1534", flag: "https://flagcdn.com/w40/je.png" },
  { code: "JO", code3: "JOR", name: "Jordan", dialCode: "+962", flag: "https://flagcdn.com/w40/jo.png" },
  { code: "KZ", code3: "KAZ", name: "Kazakhstan", dialCode: "+7", flag: "https://flagcdn.com/w40/kz.png" },
  { code: "KE", code3: "KEN", name: "Kenya", dialCode: "+254", flag: "https://flagcdn.com/w40/ke.png" },
  { code: "KI", code3: "KIR", name: "Kiribati", dialCode: "+686", flag: "https://flagcdn.com/w40/ki.png" },
  { code: "KP", code3: "PRK", name: "Korea (the Democratic People's Republic of)", dialCode: "+850", flag: "https://flagcdn.com/w40/kp.png" },
  { code: "KR", code3: "KOR", name: "Korea (the Republic of)", dialCode: "+82", flag: "https://flagcdn.com/w40/kr.png" },
  { code: "KW", code3: "KWT", name: "Kuwait", dialCode: "+965", flag: "https://flagcdn.com/w40/kw.png" },
  { code: "KG", code3: "KGZ", name: "Kyrgyzstan", dialCode: "+996", flag: "https://flagcdn.com/w40/kg.png" },
  { code: "LA", code3: "LAO", name: "Lao People's Democratic Republic (the)", dialCode: "+856", flag: "https://flagcdn.com/w40/la.png" },
  { code: "LV", code3: "LVA", name: "Latvia", dialCode: "+371", flag: "https://flagcdn.com/w40/lv.png" },
  { code: "LB", code3: "LBN", name: "Lebanon", dialCode: "+961", flag: "https://flagcdn.com/w40/lb.png" },
  { code: "LS", code3: "LSO", name: "Lesotho", dialCode: "+266", flag: "https://flagcdn.com/w40/ls.png" },
  { code: "LR", code3: "LBR", name: "Liberia", dialCode: "+231", flag: "https://flagcdn.com/w40/lr.png" },
  { code: "LY", code3: "LBY", name: "Libya", dialCode: "+218", flag: "https://flagcdn.com/w40/ly.png" },
  { code: "LI", code3: "LIE", name: "Liechtenstein", dialCode: "+423", flag: "https://flagcdn.com/w40/li.png" },
  { code: "LT", code3: "LTU", name: "Lithuania", dialCode: "+370", flag: "https://flagcdn.com/w40/lt.png" },
  { code: "LU", code3: "LUX", name: "Luxembourg", dialCode: "+352", flag: "https://flagcdn.com/w40/lu.png" },
  { code: "MO", code3: "MAC", name: "Macao", dialCode: "+853", flag: "https://flagcdn.com/w40/mo.png" },
  { code: "MG", code3: "MDG", name: "Madagascar", dialCode: "+261", flag: "https://flagcdn.com/w40/mg.png" },
  { code: "MW", code3: "MWI", name: "Malawi", dialCode: "+265", flag: "https://flagcdn.com/w40/mw.png" },
  { code: "MY", code3: "MYS", name: "Malaysia", dialCode: "+60", flag: "https://flagcdn.com/w40/my.png" },
  { code: "MV", code3: "MDV", name: "Maldives", dialCode: "+960", flag: "https://flagcdn.com/w40/mv.png" },
  { code: "ML", code3: "MLI", name: "Mali", dialCode: "+223", flag: "https://flagcdn.com/w40/ml.png" },
  { code: "MT", code3: "MLT", name: "Malta", dialCode: "+356", flag: "https://flagcdn.com/w40/mt.png" },
  { code: "MH", code3: "MHL", name: "Marshall Islands (the)", dialCode: "+692", flag: "https://flagcdn.com/w40/mh.png" },
  { code: "MQ", code3: "MTQ", name: "Martinique", dialCode: "+596", flag: "https://flagcdn.com/w40/mq.png" },
  { code: "MR", code3: "MRT", name: "Mauritania", dialCode: "+222", flag: "https://flagcdn.com/w40/mr.png" },
  { code: "MU", code3: "MUS", name: "Mauritius", dialCode: "+230", flag: "https://flagcdn.com/w40/mu.png" },
  { code: "YT", code3: "MYT", name: "Mayotte", dialCode: "+262", flag: "https://flagcdn.com/w40/yt.png" },
  { code: "MX", code3: "MEX", name: "Mexico", dialCode: "+52", flag: "https://flagcdn.com/w40/mx.png" },
  { code: "FM", code3: "FSM", name: "Micronesia (Federated States of)", dialCode: "+691", flag: "https://flagcdn.com/w40/fm.png" },
  { code: "MD", code3: "MDA", name: "Moldova (the Republic of)", dialCode: "+373", flag: "https://flagcdn.com/w40/md.png" },
  { code: "MC", code3: "MCO", name: "Monaco", dialCode: "+377", flag: "https://flagcdn.com/w40/mc.png" },
  { code: "MN", code3: "MNG", name: "Mongolia", dialCode: "+976", flag: "https://flagcdn.com/w40/mn.png" },
  { code: "ME", code3: "MNE", name: "Montenegro", dialCode: "+382", flag: "https://flagcdn.com/w40/me.png" },
  { code: "MS", code3: "MSR", name: "Montserrat", dialCode: "+1-664", flag: "https://flagcdn.com/w40/ms.png" },
  { code: "MA", code3: "MAR", name: "Morocco", dialCode: "+212", flag: "https://flagcdn.com/w40/ma.png" },
  { code: "MZ", code3: "MOZ", name: "Mozambique", dialCode: "+258", flag: "https://flagcdn.com/w40/mz.png" },
  { code: "MM", code3: "MMR", name: "Myanmar", dialCode: "+95", flag: "https://flagcdn.com/w40/mm.png" },
  { code: "NA", code3: "NAM", name: "Namibia", dialCode: "+264", flag: "https://flagcdn.com/w40/na.png" },
  { code: "NR", code3: "NRU", name: "Nauru", dialCode: "+674", flag: "https://flagcdn.com/w40/nr.png" },
  { code: "NP", code3: "NPL", name: "Nepal", dialCode: "+977", flag: "https://flagcdn.com/w40/np.png" },
  { code: "NL", code3: "NLD", name: "Netherlands (the)", dialCode: "+31", flag: "https://flagcdn.com/w40/nl.png" },
  { code: "NC", code3: "NCL", name: "New Caledonia", dialCode: "+687", flag: "https://flagcdn.com/w40/nc.png" },
  { code: "NZ", code3: "NZL", name: "New Zealand", dialCode: "+64", flag: "https://flagcdn.com/w40/nz.png" },
  { code: "NI", code3: "NIC", name: "Nicaragua", dialCode: "+505", flag: "https://flagcdn.com/w40/ni.png" },
  { code: "NE", code3: "NER", name: "Niger (the)", dialCode: "+227", flag: "https://flagcdn.com/w40/ne.png" },
  { code: "NG", code3: "NGA", name: "Nigeria", dialCode: "+234", flag: "https://flagcdn.com/w40/ng.png" },
  { code: "NU", code3: "NIU", name: "Niue", dialCode: "+683", flag: "https://flagcdn.com/w40/nu.png" },
  { code: "NF", code3: "NFK", name: "Norfolk Island", dialCode: "+672", flag: "https://flagcdn.com/w40/nf.png" },
  { code: "MP", code3: "MNP", name: "Northern Mariana Islands (the)", dialCode: "+1-670", flag: "https://flagcdn.com/w40/mp.png" },
  { code: "NO", code3: "NOR", name: "Norway", dialCode: "+47", flag: "https://flagcdn.com/w40/no.png" },
  { code: "OM", code3: "OMN", name: "Oman", dialCode: "+968", flag: "https://flagcdn.com/w40/om.png" },
  { code: "PK", code3: "PAK", name: "Pakistan", dialCode: "+92", flag: "https://flagcdn.com/w40/pk.png" },
  { code: "PW", code3: "PLW", name: "Palau", dialCode: "+680", flag: "https://flagcdn.com/w40/pw.png" },
  { code: "PS", code3: "PSE", name: "Palestine, State of", dialCode: "+970", flag: "https://flagcdn.com/w40/ps.png" },
  { code: "PA", code3: "PAN", name: "Panama", dialCode: "+507", flag: "https://flagcdn.com/w40/pa.png" },
  { code: "PG", code3: "PNG", name: "Papua New Guinea", dialCode: "+675", flag: "https://flagcdn.com/w40/pg.png" },
  { code: "PY", code3: "PRY", name: "Paraguay", dialCode: "+595", flag: "https://flagcdn.com/w40/py.png" },
  { code: "PE", code3: "PER", name: "Peru", dialCode: "+51", flag: "https://flagcdn.com/w40/pe.png" },
  { code: "PH", code3: "PHL", name: "Philippines (the)", dialCode: "+63", flag: "https://flagcdn.com/w40/ph.png" },
  { code: "PN", code3: "PCN", name: "Pitcairn", dialCode: "+64", flag: "https://flagcdn.com/w40/pn.png" },
  { code: "PL", code3: "POL", name: "Poland", dialCode: "+48", flag: "https://flagcdn.com/w40/pl.png" },
  { code: "PT", code3: "PRT", name: "Portugal", dialCode: "+351", flag: "https://flagcdn.com/w40/pt.png" },
  { code: "PR", code3: "PRI", name: "Puerto Rico", dialCode: "+1-787, +1-939", flag: "https://flagcdn.com/w40/pr.png" },
  { code: "QA", code3: "QAT", name: "Qatar", dialCode: "+974", flag: "https://flagcdn.com/w40/qa.png" },
  { code: "MK", code3: "MKD", name: "Republic of North Macedonia", dialCode: "+389", flag: "https://flagcdn.com/w40/mk.png" },
  { code: "RO", code3: "ROU", name: "Romania", dialCode: "+40", flag: "https://flagcdn.com/w40/ro.png" },
  { code: "RU", code3: "RUS", name: "Russian Federation (the)", dialCode: "+7", flag: "https://flagcdn.com/w40/ru.png" },
  { code: "RW", code3: "RWA", name: "Rwanda", dialCode: "+250", flag: "https://flagcdn.com/w40/rw.png" },
  { code: "RE", code3: "REU", name: "Réunion", dialCode: "+262", flag: "https://flagcdn.com/w40/re.png" },
  { code: "BL", code3: "BLM", name: "Saint Barthélemy", dialCode: "+590", flag: "https://flagcdn.com/w40/bl.png" },
  { code: "SH", code3: "SHN", name: "Saint Helena, Ascension and Tristan da Cunha", dialCode: "+290", flag: "https://flagcdn.com/w40/sh.png" },
  { code: "KN", code3: "KNA", name: "Saint Kitts and Nevis", dialCode: "+1-869", flag: "https://flagcdn.com/w40/kn.png" },
  { code: "LC", code3: "LCA", name: "Saint Lucia", dialCode: "+1-758", flag: "https://flagcdn.com/w40/lc.png" },
  { code: "MF", code3: "MAF", name: "Saint Martin (French part)", dialCode: "+590", flag: "https://flagcdn.com/w40/mf.png" },
  { code: "PM", code3: "SPM", name: "Saint Pierre and Miquelon", dialCode: "+508", flag: "https://flagcdn.com/w40/pm.png" },
  { code: "VC", code3: "VCT", name: "Saint Vincent and the Grenadines", dialCode: "+1-784", flag: "https://flagcdn.com/w40/vc.png" },
  { code: "WS", code3: "WSM", name: "Samoa", dialCode: "+685", flag: "https://flagcdn.com/w40/ws.png" },
  { code: "SM", code3: "SMR", name: "San Marino", dialCode: "+378", flag: "https://flagcdn.com/w40/sm.png" },
{ code: "ST", code3: "STP", name: "Sao Tome and Principe", dialCode: "+239", flag: "https://flagcdn.com/w40/st.png" },
{ code: "SA", code3: "SAU", name: "Saudi Arabia", dialCode: "+966", flag: "https://flagcdn.com/w40/sa.png" },
{ code: "SN", code3: "SEN", name: "Senegal", dialCode: "+221", flag: "https://flagcdn.com/w40/sn.png" },
{ code: "RS", code3: "SRB", name: "Serbia", dialCode: "+381", flag: "https://flagcdn.com/w40/rs.png" },
{ code: "SC", code3: "SYC", name: "Seychelles", dialCode: "+248", flag: "https://flagcdn.com/w40/sc.png" },
{ code: "SL", code3: "SLE", name: "Sierra Leone", dialCode: "+232", flag: "https://flagcdn.com/w40/sl.png" },
{ code: "SG", code3: "SGP", name: "Singapore", dialCode: "+65", flag: "https://flagcdn.com/w40/sg.png" },
{ code: "SX", code3: "SXM", name: "Sint Maarten (Dutch part)", dialCode: "+1-721", flag: "https://flagcdn.com/w40/sx.png" },
{ code: "SK", code3: "SVK", name: "Slovakia", dialCode: "+421", flag: "https://flagcdn.com/w40/sk.png" },
{ code: "SI", code3: "SVN", name: "Slovenia", dialCode: "+386", flag: "https://flagcdn.com/w40/si.png" },
{ code: "SB", code3: "SLB", name: "Solomon Islands", dialCode: "+677", flag: "https://flagcdn.com/w40/sb.png" },
{ code: "SO", code3: "SOM", name: "Somalia", dialCode: "+252", flag: "https://flagcdn.com/w40/so.png" },
{ code: "ZA", code3: "ZAF", name: "South Africa", dialCode: "+27", flag: "https://flagcdn.com/w40/za.png" },
{ code: "GS", code3: "SGS", name: "South Georgia and the South Sandwich Islands", dialCode: "+500", flag: "https://flagcdn.com/w40/gs.png" },
{ code: "SS", code3: "SSD", name: "South Sudan", dialCode: "+211", flag: "https://flagcdn.com/w40/ss.png" },
{ code: "ES", code3: "ESP", name: "Spain", dialCode: "+34", flag: "https://flagcdn.com/w40/es.png" },
{ code: "LK", code3: "LKA", name: "Sri Lanka", dialCode: "+94", flag: "https://flagcdn.com/w40/lk.png" },
{ code: "SD", code3: "SDN", name: "Sudan", dialCode: "+249", flag: "https://flagcdn.com/w40/sd.png" },
{ code: "SR", code3: "SUR", name: "Suriname", dialCode: "+597", flag: "https://flagcdn.com/w40/sr.png" },
{ code: "SE", code3: "SWE", name: "Sweden", dialCode: "+46", flag: "https://flagcdn.com/w40/se.png" },
{ code: "CH", code3: "CHE", name: "Switzerland", dialCode: "+41", flag: "https://flagcdn.com/w40/ch.png" },
{ code: "SY", code3: "SYR", name: "Syrian Arab Republic", dialCode: "+963", flag: "https://flagcdn.com/w40/sy.png" },
{ code: "TW", code3: "TWN", name: "Taiwan", dialCode: "+886", flag: "https://flagcdn.com/w40/tw.png" },
{ code: "TJ", code3: "TJK", name: "Tajikistan", dialCode: "+992", flag: "https://flagcdn.com/w40/tj.png" },
{ code: "TZ", code3: "TZA", name: "Tanzania, United Republic of", dialCode: "+255", flag: "https://flagcdn.com/w40/tz.png" },
{ code: "TH", code3: "THA", name: "Thailand", dialCode: "+66", flag: "https://flagcdn.com/w40/th.png" },
{ code: "TL", code3: "TLS", name: "Timor-Leste", dialCode: "+670", flag: "https://flagcdn.com/w40/tl.png" },
{ code: "TG", code3: "TGO", name: "Togo", dialCode: "+228", flag: "https://flagcdn.com/w40/tg.png" },
{ code: "TK", code3: "TKL", name: "Tokelau", dialCode: "+690", flag: "https://flagcdn.com/w40/tk.png" },
{ code: "TO", code3: "TON", name: "Tonga", dialCode: "+676", flag: "https://flagcdn.com/w40/to.png" },
{ code: "TT", code3: "TTO", name: "Trinidad and Tobago", dialCode: "+1-868", flag: "https://flagcdn.com/w40/tt.png" },
{ code: "TN", code3: "TUN", name: "Tunisia", dialCode: "+216", flag: "https://flagcdn.com/w40/tn.png" },
{ code: "TR", code3: "TUR", name: "Turkey", dialCode: "+90", flag: "https://flagcdn.com/w40/tr.png" },
{ code: "TM", code3: "TKM", name: "Turkmenistan", dialCode: "+993", flag: "https://flagcdn.com/w40/tm.png" },
{ code: "TC", code3: "TCA", name: "Turks and Caicos Islands", dialCode: "+1-649", flag: "https://flagcdn.com/w40/tc.png" },
{ code: "TV", code3: "TUV", name: "Tuvalu", dialCode: "+688", flag: "https://flagcdn.com/w40/tv.png" },
{ code: "UG", code3: "UGA", name: "Uganda", dialCode: "+256", flag: "https://flagcdn.com/w40/ug.png" },
{ code: "UA", code3: "UKR", name: "Ukraine", dialCode: "+380", flag: "https://flagcdn.com/w40/ua.png" },
{ code: "AE", code3: "ARE", name: "United Arab Emirates", dialCode: "+971", flag: "https://flagcdn.com/w40/ae.png" },
{ code: "GB", code3: "GBR", name: "United Kingdom", dialCode: "+44", flag: "https://flagcdn.com/w40/gb.png" },
{ code: "US", code3: "USA", name: "United States", dialCode: "+1", flag: "https://flagcdn.com/w40/us.png" },
{ code: "UY", code3: "URY", name: "Uruguay", dialCode: "+598", flag: "https://flagcdn.com/w40/uy.png" },
{ code: "UZ", code3: "UZB", name: "Uzbekistan", dialCode: "+998", flag: "https://flagcdn.com/w40/uz.png" },
{ code: "VU", code3: "VUT", name: "Vanuatu", dialCode: "+678", flag: "https://flagcdn.com/w40/vu.png" },
{ code: "VE", code3: "VEN", name: "Venezuela", dialCode: "+58", flag: "https://flagcdn.com/w40/ve.png" },
{ code: "VN", code3: "VNM", name: "Viet Nam", dialCode: "+84", flag: "https://flagcdn.com/w40/vn.png" },
{ code: "WF", code3: "WLF", name: "Wallis and Futuna", dialCode: "+681", flag: "https://flagcdn.com/w40/wf.png" },
{ code: "EH", code3: "ESH", name: "Western Sahara", dialCode: "+212", flag: "https://flagcdn.com/w40/eh.png" },
{ code: "YE", code3: "YEM", name: "Yemen", dialCode: "+967", flag: "https://flagcdn.com/w40/ye.png" },
{ code: "ZM", code3: "ZMB", name: "Zambia", dialCode: "+260", flag: "https://flagcdn.com/w40/zm.png" },
{ code: "ZW", code3: "ZWE", name: "Zimbabwe", dialCode: "+263", flag: "https://flagcdn.com/w40/zw.png" },
{ code: "AX", code3: "ALA", name: "Åland Islands", dialCode: "+358", flag: "https://flagcdn.com/w40/ax.png" }
]